CREATE SCHEMA IF NOT EXISTS library_web;

CREATE TABLE library_web.t_person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_fullname varchar(100) NOT NULL UNIQUE,
    c_birth_date int CHECK (c_birth_date > 1900 AND c_birth_date < 2024) NOT NULL,
    c_created_at timestamp NOT NULL,
    c_updated_at timestamp,
    c_created_by varchar(100) NOT NULL
);

CREATE TABLE library_web.t_book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_name varchar NOT NULL,
    c_author varchar NOT NULL,
    c_year int,
    c_person_id int REFERENCES t_person(id),
    c_owned_time TIMESTAMP
);

CREATE TABLE library_web.t_user (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_email varchar(100) NOT NULL UNIQUE,
    c_password text,
    c_authority varchar not null
)