spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/library_web
    username: postgres
    password: postgres
  flyway:
    schemas: library_web
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8081